name: CI Tests and Validation

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Set up Node.js and install dependencies
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci

      # Install Playwright browsers
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      # Run Playwright tests
      - name: Run Playwright tests
        run: npm run test:e2e

      # Run Jest tests
      - name: Run Jest tests
        run: npm run test:jest

      # Run TypeScript type checks
      - name: TypeScript Validation
        run: npm run test:types

      # Run ESLint for linting checks
      - name: Lint code with ESLint
        run: npm run lint

      # Run Prettier for code formatting checks
      - name: Check formatting with Prettier
        run: npm run prettier:check

      # Upload Playwright report as an artifact if tests fail
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
